CREATE DATABASE ecommerce_project;
USE ecommerce_project;

CREATE TABLE sales (
OrderID INT,
CustomerName VARCHAR(50),
City VARCHAR(50),
Product VARCHAR(50),
Category VARCHAR(50),
Quantity INT,
Price INT,
TotalAmount INT
); 

SELECT * FROM sales;

-- total revenue generated by the company. -- 311802183
SELECT SUM(quantity * price) AS TotalRevenue
FROM sales;

-- total orders
SELECT COUNT(*) AS Total_orders
FROM sales;

-- product category that generated the highest revenue
SELECT category,
       SUM(Quantity * Price) AS TotalRevenue
FROM sales
GROUP BY category
ORDER BY TotalRevenue DESC
LIMIT 1;

-- city that has the highest total sales revenue.
SELECT City,
	   SUM(Quantity * price) AS TotalsalesRevenue
FROM sales
GROUP BY City
ORDER BY TotalsalesRevenue DESC
LIMIT 1;

-- top 5 products with the highest quantity sold.
SELECT product,
       SUM(Quantity) AS TotalQuantity
FROM sales
GROUP BY product
ORDER BY TotalQuantity  DESC
LIMIT 5;

-- customer who placed the highest number of orders.
SELECT CustomerName,
       COUNT(*) AS Ordercount
FROM sales
GROUP BY CustomerName
ORDER BY Ordercount DESC
LIMIT 1;

-- average order value across all orders.
SELECT AVG(Price * Quantity) AS Average_Order_Value
FROM sales;

-- product that generated the highest revenue.
SELECT product,
       SUM(TotalAmount) AS TotalRevenue
FROM sales
GROUP BY product
ORDER BY TotalRevenue DESC
LIMIT 1;

-- total quantity of products sold in each category.
SELECT Category,
       SUM(Quantity) AS TotalQuantity
FROM sales
GROUP BY Product,Category;

-- top 5 customers who spent the most money.
SELECT CustomerName,
       SUM(TotalAmount) AS totalspent
FROM sales
GROUP BY customername
ORDER BY totalspent DESC
LIMIT 5;

-- city That placed the highest number of orders.
SELECT City,
       COUNT(*) AS Ordercount
FROM sales
GROUP BY City
ORDER BY ordercount DESC
LIMIT 1;

-- total revenue generated for each product category.
SELECT Category,
       SUM(TotalAmount) AS TotalRevenue
FROM sales
GROUP BY Category,Product;

-- product category that has the highest average price
SELECT Category,
       AVG(TotalAmount) AS AVGamount
FROM sales
GROUP BY Category,Product
ORDER BY AVGamount DESC
LIMIT 1;
